---
version: "3.7"
services:
  dbt-spark:
    container_name: dbt-spark
    image: spark
    ports:
      - "10000:10000"
      - "4040:4040"
    command:
      - |
        /opt/spark/sbin/start-thriftserver.sh
        /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    entrypoint: ["bash", "-c"]
    volumes:
      - ./logs:/opt/spark/log
