---
version: "3.1"
services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: airflow
    ports:
      - "25432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  kafka:
    container_name: kafka
    command:
      - |
        /etc/confluent/docker/run
        kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic news
    depends_on:
      - zookeeper
    entrypoint: ['sh', '-c']
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092'
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:29092"
    restart: always

  zookeeper:
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_TICK_TIME: 2000
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "22181:2181"
    restart: always
