---
version: "3.7"
services:
  dbt-spark:
    container_name: dbt-spark
    build: spark
    ports:
      - "10000:10000"
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    user: '0'
    command:
      - |
        /opt/spark/bin/spark-shell \
        --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2 \
        --name "Thrift JDBC/ODBC Server"
    entrypoint: ["bash", "-c"]
    volumes:
      - ./logs:/opt/spark/log
      - ./spark-warehouse:/opt/spark/work-dir/spark-warehouse
    depends_on:
      - dbt-metastore
      - minio
  dbt-metastore:
    container_name: dbt-metastore
    image: postgres:14
    ports:
      - "25432:5432"
    volumes:
      - ./metastore:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_DB=metastore
  minio:
    container_name: minio
    build: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
  trino:
    container_name: trino
    image: trinodb/trino
    ports:
      - "18080:8080"
    volumes:
      - ./thrift.properties:/etc/trino/catalog/thrift.properties
    depends_on:
      - dbt-spark
