---
version: "3.7"
services:
  dbt-spark:
    container_name: dbt-spark
    image: apache/spark-py:v3.4.0
    ports:
      - "10000:10000"
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    user: '0'
    command:
      - |
        /opt/spark/bin/spark-shell \
        --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2 \
        --name "Thrift JDBC/ODBC Server"
    entrypoint: ["bash", "-c"]
    volumes:
      - ./logs:/opt/spark/log
      - ./conf:/opt/spark/conf
      - ./jars/postgresql-42.3.8.jar:/opt/spark/jars/postgresql-42.3.8.jar
      - ./jars/delta-core_2.12-2.4.0.jar:/opt/spark/jars/delta-core_2.12-2.4.0.jar
      - ./jars/delta-storage-2.4.0.jar:/opt/spark/jars/delta-storage-2.4.0.jar
    depends_on:
      - dbt-metastore
  dbt-metastore:
    container_name: dbt-metastore
    image: postgres:14
    ports:
      - "25432:5432"
    volumes:
      - ./metastore:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_DB=metastore
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
      - MINIO_ROOT_REGION=ap-northeast-2
    command: ["server", "/data", "--console-address", ":9001"]
